### ISSUE TITLE
QWERTY Keyboard Layout

### ISSUE THREAD

**Issue by Garnek0** [elydre/profanOS#49]
Hi! I noticed there's no QWERTY keyboard layout and most people aren't used to AZERTY. My suggestion would be to use a file (`kbdconfig.txt` for example) to store the preferred keyboard layout (something like `layout=qwerty` / `layout=azerty`) and then the keyboard driver would read this file and use the selected keyboard layout. 

Also this OS is some impressive work. Good job :+1:

**Comment by elydre** [comment]
Thank you for your interest in profanOS!
there is already a keyboard layout switch with the `kb` command.
The source files are zada/keymap :)
