### ISSUE TITLE
Wow! Thank you very much!

### ISSUE THREAD

**Issue by eersoy93** [elydre/profanOS#69]
Thank you for your effort about profanOS.

I'm [E93](https://github.com/eersoy93/E93) OS developer. There is a another cfenollosa's os-tutorial OS like profanOS makes me happier. I believe, one day, E93 will have a GUI.

**Comment by elydre** [comment]
Hi @eersoy93, thank you for your feedback!

When two years ago I started profanOS from cfenollosa's tutorial I didn't think for a moment that it would become an obsession that changed my vision on computing and my way of approaching things in general :)

It's super cool that there are still OSes being born from this tuto! And I hope you have a great time developing E93!

If I can be useful for anything don't hesitate to contact me (discord: `@pf4`) and maybe olivine, profan's shell can be [ported](https://github.com/elydre/profanOS/wiki/Olivine#build-with-minimal-features) quite easily to E93, in its minimal version, you just need a memory allocator, a printf and some string management functions!

p.
